services:
  postgres16_mint:
    image: postgres:16
    container_name: postgres16_mint
    environment:
      POSTGRES_USER: mint
      POSTGRES_PASSWORD: mint
      POSTGRES_DB: mint
    ports:
      - '5409:5432'
    volumes:
      - postgres16_mint:/var/lib/postgresql/data

volumes:
  postgres16_mint:
